appName: 'Multi App pipeline. appName taken from tag'
loglevel: 'TRACE'
job:
  throttle: 5
config:
  build:
    buildEnvironment: 'int'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'int'
    deployEnvironment: 'int'
  environments:
    generic:
      appNamePrefix: 'jenkins-'
      appNamePostfix: '-helper'
      agent:
        name: 's_helper'
