appName: 'Multi App pipeline. appName taken from tag'
loglevel: 'TRACE'
job:
  throttle: 5
config:
  build:
    buildEnvironment: 'cicd_dev_only'
    # buildEnvironment: 'int'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'cicd_dev_only'
    # buildEnvironment: 'int'
    deployEnvironment: 'cicd_dev_only'
    # deployEnvironment: 'int'
  environments:
    generic:
      appNamePrefix: ''
      appNamePostfix: ''
      agent:
        name: 's_helper'
